# Setup for USB connection to PFS055YA251U6, a sensor of Leptrino.
#
# This shell script must be executed in super user privileges.

echo 'Setup udev rule for Leptrino force torque sensor.'
echo 'NOTE: this shell script must be executed in super user privileges.'

# Install udev, device management tool.
apt install libudev-dev

mkdir -p /etc/udev/rules.d

echo `# This rule is auto-generated by the shell script of leptrino-force-torque-sensor crate.` >> /etc/udev/rules.d/81-leptrino.rules
echo `# See https://github.com/Amelia10007/leptrino-force-torque-sensor-rs in detail.` >> /etc/udev/rules.d/81-leptrino.rules
echo `# Note that the following rule may be specific to PFS055YA251U6, one of the Leptrino force torque sensors.` >> /etc/udev/rules.d/81-leptrino.rules
echo `ATTRS{idVendor}=="0483", ATTRS{idProduct}=="5740", MODE="0666"` >> /etc/udev/rules.d/81-leptrino.rules

# udev must be rebooted because we modified the rule.
service udev restart
